// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iinrmahcfpbfineflook.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpbnJtYWhjZnBiZmluZWZsb29rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MjA4OTAsImV4cCI6MjA2MTA5Njg5MH0.GEAKv_OuqNFD0qnXgJQVKWuvjiBZd4KnhF1ZLeW08Tk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);